/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.inacap.inmobiliaria.frames;

import cl.inacap.inmobiliaria.dao.ClienteDAO;
import cl.inacap.inmobiliaria.dto.Cliente;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Ita
 */
public class OperacionesCliente extends javax.swing.JFrame
{
    private boolean operacion; //0 - agregar cliente, 1 - modificar
    private Cliente cliente;
    private ClienteDAO clientes = new ClienteDAO();
    
    public OperacionesCliente()
    {
        initComponents();
    }
    
    public OperacionesCliente(boolean operacion, int idCliente)
    {
        this.operacion = operacion;
        if (idCliente != 0)
            this.cliente = clientes.getCliente(idCliente);
        initComponents();
        
        //si esto es añadir un nuevo cliente
        
        if (!operacion)
        {
            clearFields();
        }
        //si esto es modificar un cliente
        if (operacion)
        {
            setFields(cliente);
        }
    }
    
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tituloLbl = new javax.swing.JLabel();
        operacionLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        compradorRadioButton = new javax.swing.JRadioButton();
        vendedorRadioButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        apellidoPatField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        apellidoMatField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ocupacionComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        nivelEscolarComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        estadoCivilComboBox = new javax.swing.JComboBox<>();
        sexoComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        diaField = new javax.swing.JTextField();
        mesField = new javax.swing.JTextField();
        añoField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        runField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comunaField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        viviendaPropiaCheckBox = new javax.swing.JCheckBox();
        creditoLbl = new javax.swing.JLabel();
        subsidioLbl = new javax.swing.JLabel();
        rentaLbl = new javax.swing.JLabel();
        porcLbl = new javax.swing.JLabel();
        creditoBancarioField = new javax.swing.JTextField();
        subsidioField = new javax.swing.JTextField();
        rentaField = new javax.swing.JTextField();
        porcRegSocField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        aceptarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        idField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                formComponentShown(evt);
            }
        });

        tituloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLbl.setText("GESTION DE CLIENTES");

        operacionLbl.setText("Operacion actual: ");
        operacionLbl.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                operacionLblComponentShown(evt);
            }
        });

        idLbl.setText("ID:");

        buttonGroup1.add(compradorRadioButton);
        compradorRadioButton.setSelected(true);
        compradorRadioButton.setText("Comprador");
        compradorRadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                compradorRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(vendedorRadioButton);
        vendedorRadioButton.setText("Vendedor");
        vendedorRadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vendedorRadioButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        jLabel4.setText("Nombre:");

        jLabel5.setText("Apellido paterno:");

        nombreField.setText("jTextField1");

        apellidoPatField.setText("jTextField2");

        jLabel6.setText("Apellido materno:");

        apellidoMatField.setText("jTextField3");

        jLabel7.setText("Ocupacion:");

        ocupacionComboBox.setModel(setOcupacionModel());

        jLabel8.setText("Nivel escolar: ");

        nivelEscolarComboBox.setModel(setNivelEscolarModel());
        nivelEscolarComboBox.setSelectedItem(setNivelEscolarModel());

        jLabel9.setText("Estado civil:");

        jLabel10.setText("Sexo:");

        estadoCivilComboBox.setModel(setEstadoCivilModel());

        sexoComboBox.setModel(setSexoModel());
        sexoComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                sexoComboBoxActionPerformed(evt);
            }
        });

        jLabel11.setText("Fecha de nacimiento: ");

        diaField.setText("jTextField4");
        diaField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                diaFieldActionPerformed(evt);
            }
        });

        mesField.setText("jTextField5");

        añoField.setText("jTextField6");

        jLabel17.setText("RUN:");

        runField.setText("jTextField11");

        jLabel1.setText("Comuna:");

        comunaField.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreField)
                            .addComponent(apellidoPatField)
                            .addComponent(apellidoMatField)
                            .addComponent(runField)
                            .addComponent(comunaField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(diaField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mesField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(añoField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexoComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ocupacionComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nivelEscolarComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estadoCivilComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(apellidoPatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(apellidoMatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(runField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comunaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(diaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ocupacionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nivelEscolarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(estadoCivilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Comprador"));

        viviendaPropiaCheckBox.setText("Posee vivienda propia");

        creditoLbl.setText("Identificador credito bancario:");

        subsidioLbl.setText("Identificador subsidio:");

        rentaLbl.setText("Renta bruta:");

        porcLbl.setText("Porcentaje en la ficha de Registro Social:");

        creditoBancarioField.setText("jTextField7");

        subsidioField.setText("jTextField8");

        rentaField.setText("jTextField9");

        porcRegSocField.setText("jTextField10");

        jLabel16.setText("%");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rentaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(creditoLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subsidioLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subsidioField)
                            .addComponent(creditoBancarioField)
                            .addComponent(rentaField)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viviendaPropiaCheckBox)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(porcLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(porcRegSocField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)))
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(viviendaPropiaCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditoLbl)
                    .addComponent(creditoBancarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subsidioLbl)
                    .addComponent(subsidioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentaLbl)
                    .addComponent(rentaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porcLbl)
                    .addComponent(porcRegSocField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)))
        );

        aceptarBtn.setText("Aceptar");
        aceptarBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarBtnActionPerformed(evt);
            }
        });

        idField.setEditable(false);
        idField.setText("jTextField1");
        idField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                idFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(operacionLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(compradorRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(vendedorRadioButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(aceptarBtn)
                .addGap(88, 88, 88)
                .addComponent(cancelarBtn)
                .addGap(0, 99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operacionLbl)
                    .addComponent(idLbl)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compradorRadioButton)
                    .addComponent(vendedorRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarBtn)
                    .addComponent(cancelarBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diaFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_diaFieldActionPerformed
    {//GEN-HEADEREND:event_diaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaFieldActionPerformed

    private void vendedorRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vendedorRadioButtonActionPerformed
    {//GEN-HEADEREND:event_vendedorRadioButtonActionPerformed
        switchPanelComprador(false);
    }//GEN-LAST:event_vendedorRadioButtonActionPerformed

    private void compradorRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_compradorRadioButtonActionPerformed
    {//GEN-HEADEREND:event_compradorRadioButtonActionPerformed
        switchPanelComprador(true);
    }//GEN-LAST:event_compradorRadioButtonActionPerformed

    private void operacionLblComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_operacionLblComponentShown
    {//GEN-HEADEREND:event_operacionLblComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_operacionLblComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentShown
    {//GEN-HEADEREND:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarBtnActionPerformed
    {//GEN-HEADEREND:event_aceptarBtnActionPerformed
        String fecha = añoField.getText() + "-" + mesField.getText() + "-" + diaField.getText();
        
        if (!operacion)
        {
            clientes.addCliente(new Cliente(
                    0, compradorRadioButton.isSelected(), nombreField.getText(), apellidoPatField.getText(), apellidoMatField.getText(), runField.getText(),
                    fecha, sexoComboBox.getSelectedIndex(), ocupacionComboBox.getSelectedIndex(), nivelEscolarComboBox.getSelectedIndex(), estadoCivilComboBox.getSelectedIndex(),
                    comunaField.getText(), viviendaPropiaCheckBox.isSelected(), Integer.parseInt(creditoBancarioField.getText()), Integer.parseInt(subsidioField.getText()),
                    Integer.parseInt(rentaField.getText()), Integer.parseInt(porcRegSocField.getText())
            ));
        }
        if (operacion)
        {
            clientes.updateCliente(new Cliente(
                    Integer.parseInt(idField.getText()), compradorRadioButton.isSelected(), nombreField.getText(), apellidoPatField.getText(), apellidoMatField.getText(), runField.getText(),
                    fecha, sexoComboBox.getSelectedIndex(), ocupacionComboBox.getSelectedIndex(), nivelEscolarComboBox.getSelectedIndex(), estadoCivilComboBox.getSelectedIndex(),
                    comunaField.getText(), viviendaPropiaCheckBox.isSelected(), Integer.parseInt(creditoBancarioField.getText()), Integer.parseInt(subsidioField.getText()),
                    Integer.parseInt(rentaField.getText()), Integer.parseInt(porcRegSocField.getText())
            ));
        }
        
        this.dispose();
        /*
        public Cliente(int idCliente, boolean comprador, String nombre, String apellidoPat, String apellidoMat, int run, 
            String fechaNac, int sexo, int ocupacion, int nivelEscolar, int estadoCivil, 
            String comuna, boolean viviendaPropia, int creditoBancario, 
            int subsidio, int rentaBruta, int porcFichaReg)
    
        */
    }//GEN-LAST:event_aceptarBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarBtnActionPerformed
    {//GEN-HEADEREND:event_cancelarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void sexoComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_sexoComboBoxActionPerformed
    {//GEN-HEADEREND:event_sexoComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoComboBoxActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_idFieldActionPerformed
    {//GEN-HEADEREND:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private DefaultComboBoxModel setSexoModel()
    {
        String[] list = clientes.getListaSexo();
        
        DefaultComboBoxModel sexoModel = new DefaultComboBoxModel();
        
        for (int i = 0; i < list.length; i++)
            sexoModel.addElement(list[i]);
        
        return sexoModel;
    }
    
    private DefaultComboBoxModel setOcupacionModel()
    {
        String[] list = clientes.getListaOcupacion();
        
        DefaultComboBoxModel ocModel = new DefaultComboBoxModel();
        
        for (int i = 0; i < list.length; i++)
            ocModel.addElement(list[i]);
        
        return ocModel;
    }
    
    private DefaultComboBoxModel setNivelEscolarModel()
    {
        String[] list = clientes.getListaNivelEscolar();
        
        DefaultComboBoxModel neModel = new DefaultComboBoxModel();
        
        for (int i = 0; i < list.length; i++)
            neModel.addElement(list[i]);
        
        return neModel;
    }
    
    private DefaultComboBoxModel setEstadoCivilModel()
    {
        String[] list = clientes.getListaEstadoCivil();
        
        DefaultComboBoxModel ecModel = new DefaultComboBoxModel();
        
        for (int i = 0; i < list.length; i++)
            ecModel.addElement(list[i]);
        
        return ecModel;
    }
    
    private void switchPanelComprador(boolean state)
    {
        jPanel2.setEnabled(state);
        viviendaPropiaCheckBox.setEnabled(state);
        creditoLbl.setEnabled(state);
        creditoBancarioField.setEnabled(state);
        subsidioLbl.setEnabled(state);
        subsidioField.setEnabled(state);
        rentaLbl.setEnabled(state);
        rentaField.setEnabled(state);
        porcLbl.setEnabled(state);
        porcRegSocField.setEnabled(state);

        if(!state)
        {
           creditoBancarioField.setText("0");
            subsidioField.setText("0");
            rentaField.setText("0");
            porcRegSocField.setText("0");
        }
    }
    
    private void clearFields()
    {
        operacionLbl.setText("Operacion actual: Agregar nuevo usuario");
        idField.setText("" + clientes.getAutoincrement());
        compradorRadioButton.setEnabled(true);
        nombreField.setText("");
        apellidoPatField.setText("");
        apellidoMatField.setText("");
        runField.setText("");
        comunaField.setText("");
        diaField.setText("");
        mesField.setText("");
        añoField.setText("");
        sexoComboBox.setSelectedIndex(0);
        ocupacionComboBox.setSelectedIndex(0);
        nivelEscolarComboBox.setSelectedIndex(0);
        estadoCivilComboBox.setSelectedIndex(0);
        viviendaPropiaCheckBox.setSelected(false);
        creditoBancarioField.setText("");
        subsidioField.setText("");
        rentaField.setText("");
        porcRegSocField.setText("");
    }
    
    private void setFields(Cliente cl)
    {
        operacionLbl.setText("Operacion actual: Modificar usuario existente");
        idField.setText("" + cl.getIdCliente());
        vendedorRadioButton.setSelected(cl.isComprador());
        nombreField.setText(cl.getNombre());
        apellidoPatField.setText(cl.getApellidoPat());
        apellidoMatField.setText(cl.getApellidoMat());
        runField.setText(""+ cl.getRun());
        comunaField.setText(cl.getComuna());
        diaField.setText(""+ cl.getFechaNac().substring(8, 10));
        mesField.setText(""+ cl.getFechaNac().substring(5, 7));
        añoField.setText(""+ cl.getFechaNac().substring(0, 4));
        sexoComboBox.setSelectedIndex(cl.getSexo());
        ocupacionComboBox.setSelectedIndex(cl.getOcupacion());
        nivelEscolarComboBox.setSelectedIndex(cl.getNivelEscolar());
        estadoCivilComboBox.setSelectedIndex(cl.getEstadoCivil());
        viviendaPropiaCheckBox.setSelected(cl.getViviendaPropia());
        creditoBancarioField.setText("" + cl.getCreditoBancario());
        subsidioField.setText("" + cl.getSubsidio());
        rentaField.setText("" + cl.getRentaBruta());
        porcRegSocField.setText("" + cl.getPorcFichaReg());
        
        if (cl.isComprador())
        {
            compradorRadioButton.setSelected(true);
            switchPanelComprador(true);
        }
        else
        {
            vendedorRadioButton.setSelected(true);
            switchPanelComprador(false);
        }
    }  
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacionesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacionesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacionesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacionesCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new OperacionesCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JTextField apellidoMatField;
    private javax.swing.JTextField apellidoPatField;
    private javax.swing.JTextField añoField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JRadioButton compradorRadioButton;
    private javax.swing.JTextField comunaField;
    private javax.swing.JTextField creditoBancarioField;
    private javax.swing.JLabel creditoLbl;
    private javax.swing.JTextField diaField;
    private javax.swing.JComboBox<String> estadoCivilComboBox;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mesField;
    private javax.swing.JComboBox<String> nivelEscolarComboBox;
    private javax.swing.JTextField nombreField;
    private javax.swing.JComboBox<String> ocupacionComboBox;
    private javax.swing.JLabel operacionLbl;
    private javax.swing.JLabel porcLbl;
    private javax.swing.JTextField porcRegSocField;
    private javax.swing.JTextField rentaField;
    private javax.swing.JLabel rentaLbl;
    private javax.swing.JTextField runField;
    private javax.swing.JComboBox<String> sexoComboBox;
    private javax.swing.JTextField subsidioField;
    private javax.swing.JLabel subsidioLbl;
    private javax.swing.JLabel tituloLbl;
    private javax.swing.JRadioButton vendedorRadioButton;
    private javax.swing.JCheckBox viviendaPropiaCheckBox;
    // End of variables declaration//GEN-END:variables
}
