/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.inacap.inmobiliaria.frames;

import cl.inacap.inmobiliaria.dao.PropiedadDAO;
import cl.inacap.inmobiliaria.dto.Propiedad;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Ita
 */
public class OperacionesPropiedad extends javax.swing.JFrame
{
    private boolean operacion; //0 - agregar cliente, 1 - modificar
    private Propiedad propiedad;
    private PropiedadDAO propiedades = new PropiedadDAO();
    
    public OperacionesPropiedad()
    {
        initComponents();
    }
    
    public OperacionesPropiedad(boolean operacion, int idPropiedad)
    {
        this.operacion = operacion;
        if (idPropiedad != 0)
            this.propiedad = propiedades.getPropiedad(idPropiedad);
        initComponents();
        
        //si esto es añadir una nueva propiedad
        
        if (!operacion)
        {
            clearFields();
        }
        //si esto es modificar una propiedad
        if (operacion)
        {
            setFields(propiedad);
        }
    }
    
         
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tituloLbl = new javax.swing.JLabel();
        operacionLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        terrenoRadioButton = new javax.swing.JRadioButton();
        inmuebleRadioButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tamañoField = new javax.swing.JTextField();
        cantConstField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        calleField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        poblacionField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comunaField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sectorComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        patioTrasCheckBox = new javax.swing.JCheckBox();
        pisosLbl = new javax.swing.JLabel();
        bañosLbl = new javax.swing.JLabel();
        dormLbl = new javax.swing.JLabel();
        pisosField = new javax.swing.JTextField();
        bañosField = new javax.swing.JTextField();
        dormitoriosField = new javax.swing.JTextField();
        patioDelCheckBox = new javax.swing.JCheckBox();
        estacionamientoCheckBox = new javax.swing.JCheckBox();
        aceptarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tasacionField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comentarioField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                formComponentShown(evt);
            }
        });

        tituloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLbl.setText("GESTION DE PROPIEDADES");

        operacionLbl.setText("Operacion actual: ");
        operacionLbl.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                operacionLblComponentShown(evt);
            }
        });

        idLbl.setText("ID:");

        buttonGroup1.add(terrenoRadioButton);
        terrenoRadioButton.setSelected(true);
        terrenoRadioButton.setText("Terreno");
        terrenoRadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                terrenoRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(inmuebleRadioButton);
        inmuebleRadioButton.setText("Inmueble");
        inmuebleRadioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                inmuebleRadioButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        jLabel4.setText("Tamaño (m2):");

        jLabel5.setText("Cantidad Construido (m2):");

        tamañoField.setText("jTextField1");

        cantConstField.setText("jTextField2");

        jLabel6.setText("Calle:");

        calleField.setText("jTextField3");

        jLabel17.setText("Poblacion");

        poblacionField.setText("jTextField11");

        jLabel1.setText("Comuna:");

        comunaField.setText("jTextField1");

        jLabel2.setText("Sector:");

        sectorComboBox.setModel(setSectorModel());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tamañoField)
                    .addComponent(cantConstField)
                    .addComponent(calleField)
                    .addComponent(poblacionField)
                    .addComponent(comunaField)
                    .addComponent(sectorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamañoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cantConstField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(calleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(poblacionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comunaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Inmueble"));

        patioTrasCheckBox.setText("Patio Trasero");

        pisosLbl.setText("Pisos:");

        bañosLbl.setText("Baños:");

        dormLbl.setText("Dormitorios:");

        pisosField.setText("jTextField7");

        bañosField.setText("jTextField8");

        dormitoriosField.setText("jTextField9");

        patioDelCheckBox.setText("Patio Delantero");

        estacionamientoCheckBox.setText("Estacionamiento");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dormLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bañosLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bañosField)
                            .addComponent(dormitoriosField)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pisosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pisosField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patioTrasCheckBox)
                    .addComponent(patioDelCheckBox)
                    .addComponent(estacionamientoCheckBox))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pisosLbl)
                        .addComponent(pisosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(patioDelCheckBox, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bañosLbl)
                    .addComponent(bañosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patioTrasCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dormLbl)
                    .addComponent(dormitoriosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estacionamientoCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        aceptarBtn.setText("Aceptar");
        aceptarBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                aceptarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarBtnActionPerformed(evt);
            }
        });

        idField.setEditable(false);
        idField.setText("jTextField1");
        idField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                idFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Tasacion:");

        tasacionField.setText("jTextField1");

        jLabel7.setText("Comentario:");

        comentarioField.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(operacionLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(terrenoRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(inmuebleRadioButton))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tasacionField)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(aceptarBtn)
                        .addGap(78, 78, 78)
                        .addComponent(cancelarBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comentarioField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operacionLbl)
                    .addComponent(idLbl)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terrenoRadioButton)
                    .addComponent(inmuebleRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tasacionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comentarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarBtn)
                    .addComponent(cancelarBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inmuebleRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_inmuebleRadioButtonActionPerformed
    {//GEN-HEADEREND:event_inmuebleRadioButtonActionPerformed
        switchPanelInmueble(true);
    }//GEN-LAST:event_inmuebleRadioButtonActionPerformed

    private void terrenoRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_terrenoRadioButtonActionPerformed
    {//GEN-HEADEREND:event_terrenoRadioButtonActionPerformed
        switchPanelInmueble(false);
    }//GEN-LAST:event_terrenoRadioButtonActionPerformed

    private void operacionLblComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_operacionLblComponentShown
    {//GEN-HEADEREND:event_operacionLblComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_operacionLblComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentShown
    {//GEN-HEADEREND:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aceptarBtnActionPerformed
    {//GEN-HEADEREND:event_aceptarBtnActionPerformed
        if (!operacion)
        {
            propiedades.addPropiedad(new Propiedad(0, "", !terrenoRadioButton.isSelected(), Integer.parseInt(tamañoField.getText()), Integer.parseInt(cantConstField.getText()), calleField.getText(),
                    poblacionField.getText(), sectorComboBox.getSelectedIndex(), comunaField.getText(), Integer.parseInt(pisosField.getText()),
                    Integer.parseInt(bañosField.getText()), Integer.parseInt(dormitoriosField.getText()), patioDelCheckBox.isSelected(), patioTrasCheckBox.isSelected(),
                    estacionamientoCheckBox.isSelected(), Integer.parseInt(tasacionField.getText()), comentarioField.getText()
            ));
            
            /*
           public Propiedad(int idPropiedad, String fechaPublicacion, boolean tipoPropiedad, int tamaño, int cantidadConstruido, String calle, 
            String poblacion, int sector, String comuna, int pisos, int baños, int dormitorios, boolean patioDel, boolean patioTras, 
            boolean estacionamiento, int tasacion,  String comentario)
    
            */
        }
        if (operacion)
        {
            propiedades.updatePropiedad(new Propiedad(Integer.parseInt(idField.getText()), "", !terrenoRadioButton.isSelected(), Integer.parseInt(tamañoField.getText()), Integer.parseInt(cantConstField.getText()), calleField.getText(),
                    poblacionField.getText(), sectorComboBox.getSelectedIndex(), comunaField.getText(), Integer.parseInt(pisosField.getText()),
                    Integer.parseInt(bañosField.getText()), Integer.parseInt(dormitoriosField.getText()), patioDelCheckBox.isSelected(), patioTrasCheckBox.isSelected(),
                    estacionamientoCheckBox.isSelected(), Integer.parseInt(tasacionField.getText()), comentarioField.getText()
            ));
        }
        
        this.dispose();
        /*
       public Propiedad(int idPropiedad, String fechaPublicacion, boolean tipoPropiedad, int tamaño, int cantidadConstruido, String calle, 
            String poblacion, int sector, String comuna, int pisos, int baños, int dormitorios, boolean patioDel, boolean patioTras, 
            boolean estacionamiento, int tasacion,  String comentario)
    */
    }//GEN-LAST:event_aceptarBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarBtnActionPerformed
    {//GEN-HEADEREND:event_cancelarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_idFieldActionPerformed
    {//GEN-HEADEREND:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private DefaultComboBoxModel setSectorModel()
    {
        String[] list = {"Norte", "Sur", "Centro", "Este", "Oeste"};
        
        DefaultComboBoxModel sexoModel = new DefaultComboBoxModel();
        
        for (int i = 0; i < list.length; i++)
            sexoModel.addElement(list[i]);
        
        return sexoModel;
    }
    
    private void switchPanelInmueble(boolean state)
    {
        jPanel2.setEnabled(state);
        patioTrasCheckBox.setEnabled(state);
        patioDelCheckBox.setEnabled(state);
        estacionamientoCheckBox.setEnabled(state);
        pisosLbl.setEnabled(state);
        pisosField.setEnabled(state);
        bañosLbl.setEnabled(state);
        bañosField.setEnabled(state);
        dormLbl.setEnabled(state);
        dormitoriosField.setEnabled(state);

        if(!state)
        {
            pisosField.setText("0");
            bañosField.setText("0");
            dormitoriosField.setText("0");
        }
    }
    
    private void clearFields()
    {
        operacionLbl.setText("Operacion actual: Agregar nueva propiedad");
        idField.setText("" + propiedades.getAutoincrement());
        terrenoRadioButton.setSelected(true);
        tamañoField.setText("");
        cantConstField.setText("");
        calleField.setText("");
        poblacionField.setText("");
        comunaField.setText("");
        sectorComboBox.setSelectedIndex(0);
        patioTrasCheckBox.setSelected(false);        
        patioDelCheckBox.setSelected(false);       
        estacionamientoCheckBox.setSelected(false);
        pisosField.setText("");
        bañosField.setText("");
        dormitoriosField.setText("");
        tasacionField.setText("");
        comentarioField.setText("");
        switchPanelInmueble(false);
    }
    
    private void setFields(Propiedad prop)
    {
        operacionLbl.setText("Operacion actual: Modificar propiedad existente");
        idField.setText("" + prop.getIdPropiedad());
        tamañoField.setText("" + prop.getTamaño());
        cantConstField.setText("" + prop.getCantidadConstruido());
        calleField.setText("" + prop.getCalle());
        poblacionField.setText("" + prop.getPoblacion());
        comunaField.setText("" + prop.getComuna());
        sectorComboBox.setSelectedIndex(prop.getSector());
        patioTrasCheckBox.setSelected(prop.isPatioTras());        
        patioDelCheckBox.setSelected(prop.isPatioDel());       
        estacionamientoCheckBox.setSelected(prop.isEstacionamiento());
        pisosField.setText("" + prop.getPisos());
        bañosField.setText("" + prop.getBaños());
        dormitoriosField.setText("" + prop.getDormitorios());
        tasacionField.setText("" + prop.getTasacion());
        comentarioField.setText("" + prop.getComentario());
        
        if (!prop.getTipoPropiedad())
        {
            terrenoRadioButton.setSelected(true);
            switchPanelInmueble(false);
        }
        else
        {
            inmuebleRadioButton.setSelected(true);
            switchPanelInmueble(true);
        }
    }  
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacionesPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacionesPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacionesPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacionesPropiedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new OperacionesPropiedad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JTextField bañosField;
    private javax.swing.JLabel bañosLbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField calleField;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JTextField cantConstField;
    private javax.swing.JTextField comentarioField;
    private javax.swing.JTextField comunaField;
    private javax.swing.JLabel dormLbl;
    private javax.swing.JTextField dormitoriosField;
    private javax.swing.JCheckBox estacionamientoCheckBox;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLbl;
    private javax.swing.JRadioButton inmuebleRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel operacionLbl;
    private javax.swing.JCheckBox patioDelCheckBox;
    private javax.swing.JCheckBox patioTrasCheckBox;
    private javax.swing.JTextField pisosField;
    private javax.swing.JLabel pisosLbl;
    private javax.swing.JTextField poblacionField;
    private javax.swing.JComboBox<String> sectorComboBox;
    private javax.swing.JTextField tamañoField;
    private javax.swing.JTextField tasacionField;
    private javax.swing.JRadioButton terrenoRadioButton;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}
